"""make book.author nullable, categories required

Revision ID: 112f66be7275
Revises: daebe9359f52
Create Date: 2026-10-09 11:59:11.504414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112f66be7275'
down_revision: Union[str, Sequence[str], None] = 'daebe9359f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('books_author_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_author_id_fkey'), 'books', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.alter_column('books', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
